Repository poporonnet/kaniwriter, pull requests merged in 2024-11, with the labels that each got.

#287 feat:コマンドの入力欄をautocompleteにした
  i18n/locales/en.json
  i18n/locales/ja.json
  src/pages/home.tsx
Labels: enhancement

#298 chore: Biomeに移行
  .eslintrc.cjs
  .eslintrc.json
  .github/workflows/ci.yml
  .prettierignore
  .prettierrc.json
  biome.json
  i18n/i18n.ts
  package.json
  pnpm-lock.yaml
  src/components/CompilerSelector.tsx
  src/components/Header.tsx
  src/components/Log.tsx
  src/components/SourceCodeTab.tsx
  src/hooks/useCompile.ts
  src/hooks/useHighlighter.ts
  src/hooks/useVersions.ts
  src/index.css
  src/libs/mrubyWriterConnector.ts
  src/pages/home.tsx
  src/routes/layout.tsx
  src/routes/router.tsx
  vite.config.ts
Labels: dependencies

#302 chore: READMEのAuthorsを更新
  README.md
Labels: documentation
